# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/speech_sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import host_app.nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/speech_sample.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1cprotobuf/speech_sample.proto\x1a\x0cnanopb.proto\"b\n\x0cSpeechSample\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\x1b\n\x0cpkts_encoded\x18\x02 \x02(\rB\x05\x92?\x02\x38\x10\x12\"\n\x07samples\x18\x03 \x03(\rB\x11\x92?\x02\x38\x10\x92?\x03\x10\x80\x01\x92?\x03\x80\x01\x01'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_SPEECHSAMPLE = _descriptor.Descriptor(
  name='SpeechSample',
  full_name='SpeechSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SpeechSample.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pkts_encoded', full_name='SpeechSample.pkts_encoded', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='SpeechSample.samples', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020\222?\003\020\200\001\222?\003\200\001\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['SpeechSample'] = _SPEECHSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeechSample = _reflection.GeneratedProtocolMessageType('SpeechSample', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHSAMPLE,
  '__module__' : 'protobuf.speech_sample_pb2'
  # @@protoc_insertion_point(class_scope:SpeechSample)
  })
_sym_db.RegisterMessage(SpeechSample)


_SPEECHSAMPLE.fields_by_name['pkts_encoded']._options = None
_SPEECHSAMPLE.fields_by_name['samples']._options = None
# @@protoc_insertion_point(module_scope)
